= B5 Documentation
:toc:
:toclevels: 3
:sectnums:
:stem:

== B5: Underflow and Near Underflow

Aharoni et al.

=== Description
This model creates a test-case for each of the following constraints on the intermediate results:

Test 1):: A random positive SubNorm

Test 2):: A random negative SubNorm

Test 3):: All numbers in the range [+ MinSubNorm - 3 ulp, + MinSubNorm + 3 ulp]

Test 4):: All numbers in the range [- MinSubNorm - 3 ulp, - MinSubNorm + 3 ulp]

Test 5):: All numbers in the range [ + MinNorm - 3 ulp, + MinNorm + 3 ulp]

Test 6):: All numbers in the range [- MinNorm - 3 ulp, - MinNorm + 3 ulp]

Test 7):: A random number in the range (0, MinSubNorm)

Test 8):: A random numnber in the range (-MinSubNorm, -0)

Test 9):: One number for every exponent in the range [MinNorm.exp, MinNorm.exp + 5]

*Number of tests:* 2 E 5

*Precisions Supported:* `BF_16`, `FP_16`, `FP_32`, `FP_64`, `FP_128`

*Operations Supported:* `All`

== Implementation

=== Definitions
`min_exp`:: The minimum normal exponent for each precision, where the biased exponent value is 1.
`lp/hp`:: This test suite will be performing high to low precision converts to trigger underflow. hp refers to the input operand for these operations, the higher precision input. lp refers to the lower precision output of the conversion.
`hp_exp/lp_exp`:: The exponent value for hp and lp respectively.
`lp_sn_exp`:: The exponent value corresponding to a subnormal value for lp. In any precision, this is 0 when represented as a biased exponent. In most tests, the mathematical operations will be expressed where lp_sn_exp is unbiased.
`lp_max_sn`:: The largest possible subnormal value for the lp, the exponent is lp_sn_exp, the mantissa is all 1s.
`lp_min_sn`:: The smallest representable subnormal value for lp, the exponent is lp_sn_exp, the mantissa is all 0s except for a 1 in the ulp.
`m_bits`:: The number of mantissa bits, depends on the precision.
lp_m_bits/hp_m_bits: The number of m_bits for lp/hp, respectively.
`hp_min_exp`:: The lowest exponent value for hp in order to trigger underflow after a conversion.
`hp_max_exp`:: The highest exponent value for hp in order to trigger underflow after a conversion.
`ulp`:: Aharoni defines 1 ulp as “the value of a 1 in the last place of a number representation. For the binary floating-point number: b0.b1b2…bk * 2m, ulp = 1 * 2m-k” (Aharoni, 10). Within this definition, m represents the bit number within the mantissa and k represents the unbiased exponent. While this definition of ulp is utilized within Aharoni’s description of tests 3 - 6, in the B5 test suite, it is not always possible to achieve a value of -3 ulp. Additionally, B5 is testing various intermediate values and the definition of m used within the Aharoni definition is dependent on the operation being performed and the precision involved. The interesting test cases for underflow are where the values of the effective least significant bit (L’), rounding bit (R’), and fist sticky bit (T’) can alter the result after rounding. Based on the rounding mode, various combinations of  L’, R’, and T’ can trigger the RND representable, which truncates the value and adds 1 to L’ (RISC-V System-on-Chip Design, by Harris, Stine, Thompson, and Harris). Therefore, the definition, ulp was added to represent the various representations of L’, R’, and T’ which trigger the RND rounding function based on the rounding mode. ulp is defined as 1 * 2m-k-2 where m represents the exponent and k represents the mantissa bits based on the precision. This is the first bit of the sticky bit, 2 positions beneath the lsb.
`msb_exp`:: The exponent value for the most significant bit.

== Operations

=== One operand
* FP_128 -> FP_64 | FP_128 -> FP_32 | FP_128 → FP_16 | FP_128 → BF_16
* FP_64 -> FP_32 | FP_64 -> FP_16 | FP_64 -> FP_16|FP_64 -> BF_16
* FP_32 -> FP_16 | FP_32 -> BF_16
* FP_16 -> BF_16

=== Two operands
* Multiply
* Divide

=== Three operands
* FMADD
* FMSUB
* FNMSUB
* FNMADD

=== Rounding Modes
* Round Near Even
* Round To Min Mag
* Round To Min
* Round To Max
* Round Near Max Mag
* Round To Odd

=== Description
This model will generate test-cases which seek to ensure that a RISC-V processor properly sets the Underflow flag. IEEE 754 defines two events in which an underflow flag can occur. One is the creation of a tiny nonzero result. The other is a loss of accuracy in approximating these tiny results. Regarding the creation of a tiny nonzero result, IEEE 754 defines two ways in which this tiny result can be detected:

* “After rounding - when a nonzero result computed as though the exponent range were unbounded would lie strictly between +- 2Emin”
* “Before rounding - when a nonzero result computed as though both the exponent range and the precision were unbounded would lie strictly between +-2Emin”.

Regarding loss of accuracy, IEEE 754 defines the two ways in which a loss of accuracy can be detected:

* “A denormalization loss - When the delivered result differs from what would have been computed were the exponent range unbounded”
* “An Inexact Result - When the delivered result differs from what would have been computed were both exponent range and precision unbounded (This is the condition called inexact in 7.5)”.

Loss of accuracy will be defined by an inexact result. An inexact result is detected by monitoring R’ and T’, the effective rounding bit and sticky bit after a possible normalization shift, respectively (RISC-V System-on-Chip Design, by Harris, Stine, Thompson, and Harris). This model includes 158 interesting tests which are tiny and inexact before rounding and not tiny after rounding. This results in underflow flag if tininess is detected before rounding, but no underflow flag if tininess is detected after rounding.

The following includes a half precision binary representation of the desired mantissa combinations where stem:["m_bits" = 10]. * represents any random series of mantissa bits

[[MinSubNorm]]
==== MinSubNorm +- 3 ulp
[cols="4*"]
|===
| ulp increment | msb_exp | biased exp | Intermediate Mantissa

|- 3 ulp | stem:["min_exp" - "m_bits"]     | 0 | 0000_0000_00 1*
|- 2 ulp | stem:["min_exp" - "m_bits"]     | 0 | 0000_0000_00 10
|- 1 ulp | stem:["min_exp" - "m_bits"]     | 0 | 0000_0000_00 1*
|  0 ulp | stem:["min_exp" - "m_bits" + 1] | 0 | 0000_0000_01 00
|+ 1 ulp | stem:["min_exp" - "m_bits" + 1] | 0 | 0000_0000_01 0*
|+ 2 ulp | stem:["min_exp" - "m_bits" + 1] | 0 | 0000_0000_01 10
|+ 3 ulp | stem:["min_exp" - "m_bits" + 1] | 0 | 0000_0000_01 1*

|===

[[MinNorm]]
==== MinNorm +- 3 ulp
[cols="3*"]
|===
| ulp increment | biased exp | Intermediate Mantissa

|- 3 ulp | 0 | 1111_1111_11 01
|- 2 ulp | 0 | 1111_1111_11 10
|- 1 ulp | 0 | 1111_1111_11 1*
|  0 ulp | 1 | 0000_0000_01 00
|+ 1 ulp | 1 | 0000_0000_01 0*
|+ 2 ulp | 1 | 0000_0000_01 10
|+ 3 ulp | 1 | 0000_0000_01 1*

|===
[[Factors]]
==== MinNorm +- 3ulp Mantissa Values
[cols="1,2,4", options="header"]
|===
| Precision | ULP Increment | Product

| FMT_BF16 | +1 ulp | stem:[(8 + 1) * (8^2 - 8 + 1)]
| FMT_HALF | +1 ulp | stem:[(2^4 + 1) * ((2^4)^2 - 2^4 + 1)]
| FMT_SINGLE | +1 ulp | stem:[(2^5 + 1) * ((2^5)^4 - (2^5)^3 + (2^5)^2 - 2^5 + 1)]
| FMT_DOUBLE | +1 ulp | stem:[(2^(11) + 1) * ((2^(11))^4 - (2^(11))^3 + (2^(11))^2 - 2^(11) + 1)]
| FMT_QUAD | +1 ulp | stem:[(2^(38) + 1) * (2^(76) - 2^(38) + 1)]

| FMT_BF16 | +2 ulp | Prime
| FMT_HALF | +2 ulp | stem:[2^(11) + 1]
| FMT_SINGLE | +2 ulp | stem:[(2^8 + 1) * ((2^8)^2 - 2^8 + 1)]
| FMT_DOUBLE | +2 ulp | stem:[2^(53) + 1]
| FMT_QUAD | +2 ulp | stem:[2^(113) + 1]

| FMT_BF16 | +3 ulp | stem:[2^9 + 2 + 1]
| FMT_HALF | +3 ulp | stem:[2^(13) + 4 + 3]
| FMT_SINGLE | +3 ulp | stem:[2^(26) + 7]
| FMT_DOUBLE | +3 ulp | stem:[2^(55) + 7]
| FMT_QUAD | +3 ulp | stem:[(2^(112) + 2) * (2^(113) - 2)]

| FMT_BF16 | -1 ulp | stem:[2^(14) - 1]
| FMT_HALF | -1 ulp | stem:[2^(20) - 1]
| FMT_SINGLE | -1 ulp | stem:[2^(46) - 1]
| FMT_DOUBLE | -1 ulp | stem:[2^(104) - 1]
| FMT_QUAD | -1 ulp | stem:[2^(224) - 1]

| FMT_BF16 | -2 ulp | stem:[2^8 - 1]
| FMT_HALF | -2 ulp | stem:[2^(11) - 1]
| FMT_SINGLE | -2 ulp | stem:[2^(24) - 1]
| FMT_DOUBLE | -2 ulp | stem:[2^(53) - 1]
| FMT_QUAD | -2 ulp | stem:[2^(113) - 1]

| FMT_BF16 | -3 ulp | stem:[19 * 107]
| FMT_HALF | -3 ulp | stem:[233 * 281]
| FMT_SINGLE | -3 ulp | stem:[479 * 70051]
| FMT_DOUBLE | -3 ulp | stem:[497401731493 * 36217]
| FMT_QUAD | -3 ulp | stem:[613 * 33881219305284356466756909162937]
|===
== Specific Test Procedure

=== Operation: Multiplication
==== General Procedure
Multiplication of floating point numbers `a` and `b` to get `c` takes the following form: stem:[(1."mantissa_a") * (1."mantissa_b") * 2^("a_exp" + "b_exp") * -1^("a_sign" oplus "b_sign") = "c_mantissa" * 2^"c_exp" * -1^"c_sign"]. Each test has a different requirement on `c` which dictates the possible values for the input values `a` and `b`.

==== Tests 1, 2, 3, and 4
For tests 1 and 2, stem:["c_exp" <= "minExp"]. For tests 3 and 4, stem:["c_exp" = "msb_exp"] as listed in xref:MinSubNorm[MinSubNorm &#177; 3 ulp]. The values `a_exp` and `b_exp` must satisfy the equation: stem:["a_exp" + "b_exp" = "c_exp"]. To satisfy this equation, stem:["a_exp" = "random(min_sn, c_exp - min_sn)"] such that the largest value `b_exp` can be is stem:["target" + "min_sn"]. Therefore, stem:["b_exp" = "c_exp" - "a_exp"].
Tests 1 and 2 have no requirements on the mantissa, so `a_mantissa` and `b_mantissa` are randomly generated values which do not result in a normalization shift.
`a_mantissa` and `b_mantissa` are randomly generated values which result in multiplication as indicated by xref:MinSubNorm[MinSubNorm &#177; 3 ulp].
`a_sign` and `b_sign` are randomly generated based on the test's requirements on the `c_sign`.`

==== Tests 5 and 6
`a_exp` and `b_exp` are randomly generated such that stem:["a_exp" + "b_exp" = "c_exp"] where `c_exp` matches the exponent value indicated by xref:MinNorm[MinNorm &#177; 3 ulp].
Each `c_mantissa` pattern indicated within xref:MinNorm[MinNorm &#177; 3 ulp] was determined as specified by xref:Factors[Tests 5 and 6 Specific Products]. BF_16 + 2 ulp was excluded because it is prime.
`a_sign` and `b_sign` are randomly generated based on each test's requirements on `c_sign`.

==== Tests 7 and 8
`a_exp` and `b_exp` are randomly generated such that stem:["a_exp" + "b_exp" < "min_exp"]. `a_mantissa` and `b_mantissa` are fully randomized and such that their product, `c_exp` does not require a normalization shift. `a_sign` and `b_sign` are randomized such that for Test 7, stem:["a_sign" oplus "b_sign" = -1] and for Test 8, stem:["a_sign" oplus "b_sign" = +1]

==== Test 9
`a_exp` and `b_exp` are randomly generated such that stem:["a_exp" + "b_exp" \exists \in S, S = \{"min_exp",...,"min_exp + 5"}]
`a_mantissa` and `b_mantissa` are randomly generated such that their product does not require a normalization shift.
`a_sign` and `b_sign` generation are fully randomized.

==== General Form
High precision to low precision floating point converts take an input operand, `hp` and output the result, `lp`.

==== Determining hp_sign
The desired result's sign, `lp_sign` must match what is defined in <<Desired Sign>>. Performing a convert preserves the sign, so stem:["hp_sign" = "output_sign"].

==== Determining hp_exp
The desired result's exponent, `lp_exp` must match what is defined in <<Desired Exponent>>. Performing a convert preserves the exponent as long as the exponent is normal before and after the convert or subnormal before and after (provided that both `hp` and `lp` share the same `min_exp`). Otherwise, if a transition from normal to subnormal is made, which occurs when stem:["hp_min_exp" < "hp_exp" < "lp_min_exp"], conversions limit the exponent to `lp_min_exp`. Therefore, stem:["hp_min_exp" = max("output_exp", "lp_min_exp")]

==== Determining hp_mantissa
The desired result's mantissa, `lp_mantissa` must match what is defined in <<Desired Mantissa>>. As described in <<Determining hp_exp>>, `hp_exp` may represent a subnormal value in `hp`, meaning that the number of bits left to generate the desired mantissa pattern is not `m_bits`. The variable representing the actual number of bits left, `bits_left` is calculated as follows: stem:["bits_left" = "hp_m_bits" - max("hp_min_exp" - "input_exp", 0)]. Because it is impossible to go from subnormal in `hp` to normal in `lp`, I can fill the mantissa bits according to <<Desired Mantissa>>. If `hp_exp` is normal in `hp`, the first bit out of the LSB, rounding, and sticky bit will be satisfied after the conversion into `lp`. All bits of `hp_mantissa` will be determined based on the pattern of all following bits.

=== Operations: Multiplication

==== General Form
Multiplication of floating point numbers `a` and `b` to get `c` takes the following form: stem:[(1."mantissa_a") * (1."mantissa_b") * 2^("a_exp" + "b_exp") * -1^("a_sign" oplus "b_sign") = "c_mantissa" * 2^"c_exp" * -1^"c_sign"]. Each test has a different requirement on `c` which dictates the possible values for the input values `a` and `b`.

==== Determining the input signs

The desired value for `c_sign` matches the desired sign as stated in <<Output Sign>>.  If `c_sign`=0, `a_sign` is randomly generated and stem:["b_sign" = "a_sign"]. If `c_sign` =1, `a_sign` and `c_sign` are randomly generated and stem:["b_sign" = ("a_sign" + 1) % 2].

==== Determining the input exponents
The desired value for `c_exp` matches the exponent as stated in <<Desired Exponent>>. The values `a_exp` and `b_exp` must satisfy the equation: stem:["a_exp"+"b_exp"="c_exp"]. To satisfy this equation, stem:["a_exp" = random("min_sn", "c_exp" - "min_sn")] such that the largest value `b_exp` can be is stem:["target" + "min_sn"]. Therefore, stem:["b_exp" = "c_exp" - "a_exp"].

==== Determining the input mantissas
The desired value for `c_mantissa` matches the mantissa as stated in <<Desired Mantissa>>. Choosing the appropriate values `a_mantissa` and `b_mantissa` will depend on `lrs_int`.  If `lrs_int` = 1, `a_mantissa` and `b_mantissa` are randomly generated within in the range stem:[[1, 2^"bits_left")]. To ensure that `c_mantissa` < 2 and no normalization shift is required, `a_mantissa` and `b_mantissa` are regenerated until the result satisfies the inequality: stem:["a_mantissa" * "b_mantissa" < 2^("a_mantissa_bits" + "b_mantissa_bits" - 1)]. If `lrs_int` = 3, 5, or 7, mantissa generation occurs until the required equality on the lsb and rounding bits are satisfied. If `lrs_int` = 2 or 4, `a_mantissa` or `b_mantissa` is randomly assigned a value in the range stem:[2^("bits left" -1)].  If `lrs_int` = 6, `a_mantissa` or `b_mantissa` is randomly incremented by stem:[2^("bits_left" - 2)].

=== Operations: Division

==== General Form

Division of floating point numbers `a` and `b` resulting in the floating point value `c` take the following form: stem:["c_mantissa" * 2^"c_exp" * -1^"c_sign" = (1."mantissa_a") / (1."mantissa_b") * 2^("a_exp" - "b_exp") * -1^("a_sign" oplus "b_sign")].

==== Determining the input signs
Procedure identical to that listed in <<Determining the input signs>>.

==== Determining the input exponent
The desired value for `c_exp` matches the exponent as stated in <<Desired Exponent>>. To avoid normalization after division, stem:["a_mantissa" > "b_mantissa"]. Because floating point adds a hidden 1 to normalized values, this means that a cannot be subnormal when `b` is normal. To avoid this condition, `a_exp` and `b_exp` are restricted to normal exponents. To satisfy the equation that stem:["c_exp" = "a_exp" - "b_exp"], the possible range of `a_exp` is first determined. stem:["a_exp" = "random"(max("min_sn", "min_sn" + "c_exp"), min("max_exp", "max_exp" + "c_exp"))]. With `a_exp` determined, stem:["b_exp" = "a_exp" - "c_exp"].

==== Determining the input mantissas
The desired value for `c_mantissa` matches the mantissa as stated in <<Desired Mantissa>>. If `lrs_int` = 2 or `lrs_int` = 4 the only way to satisfy the requirement on `c_mantissa` is to ensure that the first bit in the mantissa is a 1 and all lower bits are 0. If `lrs_int` = 1, then `a_mantissa` and `b_mantissa` = stem:["random" [1, 2^"m_bits"-1)]. If `lrs_int` = 6, then stem:["a_mantissa" = 2^("m_bits" - 1)] and the first bit in `b_mantissa` is a 1 with all lower bits being 0. If `lrs_int` = 5, then the following inequality must be satisfied: stem:[1 < "a"/"b" <3/2] If `lrs_int` = 7, then the following inequality must be satisfied: stem:[3/2<"a"/"b"<2]. Because `a` and `b` have the same range of possible values inequality around `a`/`b` greater than or less than 3/2 this test simply creates two values, a larger and a smaller value to represent the possible representations of `a`/`b`. The smaller value is within the range: stem:[(1, (2* ((2^"bits_left") -1))/3))]. Based on the smaller value, the large value lies within the range: stem:[(3/2* "small value", (2^"bits_left") - 1)]. If `lrs_int` = 5, `a_mantissa` = the smaller value and `b_mantissa` = the larger value. If `lrs_int` = 7, `a_mantissa` = the larger value and `b_mantissa` = the smaller value.

=== Operations: All fused multiply operations
==== General Form
Floating point FMA operations of the operands `a1`, `a2`, and `b` take the form:

* FMADD: stem:["c" = ("a1" * "a2") + "b"]
* FMSUB: stem:["c" = ("a1" * "a2") - "b"]
* FNMSUB: stem:["c" =-("a1" * "a2") + "b"]
* FNMADD: stem:["c" =-("a1" * "a2") - "b"]

Each test has a different requirement on `c`, which determines the possible values for the inputs, `a1`, `a2`, and `b`.
==== Determining input signs
The value of `c_sign` matches the sign as stated in <<Desired Sign>>. Each FMA operation results in a different sign as a result of the multiplication and addition operation. Because the multiplication result can reach below `min_sn` but the addition operation is capped at `min_sn`, the sign of the addition dictates the sign of FMA operation. Therefore, based on the FMA operation being performed, the input sign of `b` is altered such that stem:["b_sign" = "c_sign"]. Because the smallest value of `b` is `min_sn`, and each test case seeks results below `min_sn`, the result of the multiplication must be the opposite of `b_sign`. Therefore, based on the FMA operation being performed, `a1_sign` and `a2_sign` are determined such that stem:[("a1_sign" oplus "a2_sign") oplus "multiplication sign" = ! "b_sign"]. Where multiplication sign represents 1 for FNMSUB and FNMADD and 0 for FMSUB and FMADD.

==== Determining input exponent and mantissa

The desired output sign and exponent, `c_sign` and `c_exp` match the values as stated in <<Desired Sign>> and <<Desired Exponent>> respectively. Within tests 1 and 3 where the magnitude of the FMA operation lies between `minSubNorm` and `minSubNorm`/2, stem:["b" = "minSubNorm" * 2]. For tests 2 and 4 where the magnitude of the FMA operation lies between 0 and `minSubNorm`/2, stem:["b" = "minSubNorm"]. As observed in <<Desired Mantissa>>, each test has a different desired lsb, rounding bit, and sticky bit pattern, which can be represented as lrs_int. Since the value of `b` is determined, the bit pattern of `b` can also be represented as an integer. Regardless of the test, the integer representation of `b`, `b_int` is 8. The signs of each multiplication operation, as shown in <<Determining input signs>> are an effective subtraction from the addition operation. We can use the desired output `lrs_int` and `b_int` to determine the desired bit pattern of the multiplication operation, `mul_int`. Using the equation: stem:["b_int" - "lrs_int" = "mul_int"], the desired bit pattern of the multiplication is determined. This value `mul_int` is then passed into the multiplication procedure as `lrs_int` and the results are stored as `a1` and `a2`.

== Test Count Breakdown
=== Number of Operations
[cols="4,1", options="header"]
|===
| Operation Type | Count

| One operand | 10
| Two operands | 2
| Three operands | 4
| *Total* | *16*
|===

=== Configurations
[cols="4,1", options="header"]
|===
| Parameter | Count

| Number of precisions | 5
| Rounding Modes | 5
|===

=== Vectors Generated per Test
[cols="3*", options="header"]
|===
| Test # | Condition | Count |

1 | A random positive SubNorm | 1 |

2 | A random negative SubNorm | 1 |

3 | All numbers in the range [+ MinSubNorm - 3 ulp, + MinSubNorm + 3 ulp] | 7 |

4 | All numbers in the range [- MinSubNorm - 3 ulp, - MinSubNorm + 3 ulp] | 7 |

5 | All numbers in the range [ + MinNorm - 3 ulp, + MinNorm + 3 ulp] | 7 |

6 | All numbers in the range [- MinNorm - 3 ulp, - MinNorm + 3 ulp] | 7 |

7 | A random number in the range (0, MinSubNorm) | 1 |

8 | A random numnber in the range (-MinSubNorm, -0) | 1 |

9 | One number for every exponent in the range [MinNorm.exp, MinNorm.exp + 5] | 6 |


| *Total* | *38*
|===

=== Total Test Count
[cols="3*", options="header"]
|===
| Scenario | Breakdown | Count
|Multiplication | (38 * 5 * 5) - (2 * 5) | 940
|Division | (24 * 5 * 5) | 600
|Converts | (10 * 5 * 38) | 1900
|Add/Sub  | (12 * 5 * 5) | 300
|FMA      | (38 * 5 * 5 * 4) | 3800
| *Total Tests* | *7540*
|===

_*Differs from Aharoni test count_
