# Source: jcarlin@hmc.edu on 19 Feb 2026
# Modified by rwolk@hmc.edu on 6 Jul 2026

name: CI

on:
  push:
  pull_request:

# Only run CI on the latest commit if a PR is updated
concurrency:
  group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}"
  cancel-in-progress: true

jobs:
  lint:
    name: Pre-commit check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          submodules: 'true'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3 # v8.3.0

      - name: Ensure pre-commit checks pass
        run: uvx pre-commit run --all-files --show-diff-on-failure --color=always

  testgen:
    name: Run all Test Generation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          submodules: 'true'

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@d31148d669074a8d0a63714ba94f3201e7020bc3 # v8.3.0

      - name: Generate Tests
        run: make all
